# Generated by Django 5.2.15 on 2026-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntelligenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("source", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("severity", models.CharField(default="Low", max_length=50)),
                ("created_at", models.DateTimeField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
