# Generated by Django 5.2.15 on 2026-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intelligencerecord",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="intelligencerecord",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="intelligencerecord",
            name="severity",
            field=models.CharField(default="Medium", max_length=50),
        ),
    ]
